"""Populate SnapVault with demo albums and photos.

Runs against whichever backend is active — local JSON + filesystem by
default, or DynamoDB + S3 when SNAPVAULT_BACKEND=aws. The images are
generated on the fly (small gradient PNGs), so no internet or sample
files are needed and the demo gallery is never empty.

    # local (default)
    python seed.py

    # straight into the cloud resources, from Cloud9
    SNAPVAULT_BACKEND=aws SNAPVAULT_BUCKET=<your-bucket> python seed.py
"""
import io
import re
import struct
import zlib

from app.models import Album, Photo
from app.repos import build_repo
from app.storage import build_storage


def make_gradient_png(w, h, c1, c2):
    """Dependency-free RGB PNG writer producing a vertical gradient."""
    def chunk(typ, data):
        body = typ + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xffffffff)

    raw = bytearray()
    for y in range(h):
        raw.append(0)  # filter type: none
        t = y / max(1, h - 1)
        r = int(c1[0] + (c2[0] - c1[0]) * t)
        g = int(c1[1] + (c2[1] - c1[1]) * t)
        b = int(c1[2] + (c2[2] - c1[2]) * t)
        raw += bytes((r, g, b)) * w
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b""))


def _slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "photo"


# album name -> list of (title, tags, color_from, color_to, favorite?)
DEMO = {
    "Nature": [
        ("Forest path", "nature, green, trees", (28, 120, 70), (170, 215, 110), True),
        ("Golden sunset", "nature, sunset, sky", (255, 153, 51), (120, 40, 120), False),
        ("Ocean calm", "nature, sea, blue", (16, 78, 139), (130, 200, 230), True),
        ("Mountain haze", "nature, mountain", (90, 100, 120), (210, 215, 225), False),
    ],
    "City": [
        ("Skyline", "city, buildings", (40, 44, 70), (120, 130, 180), False),
        ("Night lights", "city, night, neon", (20, 16, 40), (200, 60, 160), True),
        ("Old street", "city, street", (110, 95, 80), (210, 195, 170), False),
    ],
    "Abstract": [
        ("Violet flow", "abstract, violet", (109, 94, 252), (180, 120, 255), True),
        ("Warm fade", "abstract, warm", (240, 110, 60), (250, 200, 120), False),
        ("Cool mist", "abstract, cool", (40, 160, 170), (180, 230, 230), False),
    ],
}


def run():
    repo = build_repo()
    storage = build_storage()
    total = 0

    for album_name, photos in DEMO.items():
        album = Album.new(album_name)
        repo.albums.save(album)
        for title, tags, c1, c2, fav in photos:
            png = make_gradient_png(480, 320, c1, c2)
            photo = Photo.new(album_id=album.id, title=title, tags=tags,
                              description="Demo photo generated by seed.py.")
            name = _slug(title) + ".png"
            key = "albums/%s/%s-%s" % (album.id, photo.id, name)

            # upload through the storage layer (S3 in aws mode, fs locally)
            storage.save(key, io.BytesIO(png), "image/png")

            photo.file_key = key
            photo.file_name = name
            photo.content_type = "image/png"
            photo.size = str(len(png))
            photo.favorite = "1" if fav else "0"
            repo.photos.save(photo)
            total += 1
        print("seeded album '%s' (%d photos)" % (album_name, len(photos)))

    print("Done — %d albums, %d photos." % (len(DEMO), total))


if __name__ == "__main__":
    run()
